server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 5000

# ERROR > WARN > INFO > DEBUG > TRACE
logging:
  level:
    root: WARN
    com.tenco.blog: INFO           # 운영 시 중요한 로그만